# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # VM1 - Servidor DNS maestro
  config.vm.define "maestro" do |maestro|
    maestro.vm.hostname = "maestro"
    maestro.vm.network "private_network", ip: "192.168.50.2",
      virtualbox__intnet: "red-parcial"
    maestro.vm.provision "shell", path: "provision_dns.sh"
  end

  # VM2 - Servidor DNS esclavo
  config.vm.define "esclavo" do |esclavo|
    esclavo.vm.hostname = "esclavo"
    esclavo.vm.network "private_network", ip: "192.168.50.3",
      virtualbox__intnet: "red-parcial"
    esclavo.vm.provision "shell", path: "provision_dns.sh"
  end

  # VM3 - Cliente y servidor web
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.50.10",
      virtualbox__intnet: "red-parcial"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provision "shell", path: "provision_web.sh"
  end
end